server:
  port: 9000

sql:
  base-package: com.mall.domain.entity.*

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.165.148:3306/mall_infrastructure?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ${password}

minio:
  access-key: ${minio_ak}
  secret-key: ${minio_sk}
  end-point: http://124.222.165.148:9000
  bucket: my-mall
